<?php
/**
 * @file
 * Code for the YSGA Base Config feature.
 */

include_once 'ysga_base_config.features.inc';

/**
 * Implements hook_date_formats().
 */
function ysga_base_config_date_formats() {
  return array(
    // Creates a new format for a new, custom format type.
    array(
      'type' => 'ysga_date_only',
      'format' => 'j \d\e F \d\e Y',
      'locales' => array(),
    ),
  );
}

/**
 * Implements hook_date_format_types().
 */
function ysga_base_config_date_format_types() {
  return array(
    'ysga_date_only' => t('Date only'),
  );
}