<?php
/**
 * @file
 * ysga_context_resultados.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function ysga_context_resultados_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: menu-resultados-consulta_campaa-de-divulgacin-de-derechos-ciudadanos-en-el-marco-del-gobierno-abierto:node/78
  $menu_links['menu-resultados-consulta_campaa-de-divulgacin-de-derechos-ciudadanos-en-el-marco-del-gobierno-abierto:node/78'] = array(
    'menu_name' => 'menu-resultados-consulta',
    'link_path' => 'node/78',
    'router_path' => 'node/%',
    'link_title' => 'Campaña de divulgación de derechos ciudadanos en el marco del gobierno abierto',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-resultados-consulta_campaa-de-divulgacin-de-derechos-ciudadanos-en-el-marco-del-gobierno-abierto:node/78',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'menu-resultados-consulta_participacin-ciudadana:<nolink>',
  );
  // Exported menu link: menu-resultados-consulta_catlogo-institucional-y-gua-de-acceso-ciudadano:node/81
  $menu_links['menu-resultados-consulta_catlogo-institucional-y-gua-de-acceso-ciudadano:node/81'] = array(
    'menu_name' => 'menu-resultados-consulta',
    'link_path' => 'node/81',
    'router_path' => 'node/%',
    'link_title' => 'Catálogo institucional y guía de acceso ciudadano',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-resultados-consulta_catlogo-institucional-y-gua-de-acceso-ciudadano:node/81',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'menu-resultados-consulta_transparencia:<nolink>',
  );
  // Exported menu link: menu-resultados-consulta_directriz-para-el-cumplimiento-efectivo-del-derecho-de-acceso-a-la-informacin-pblica-en-el-poder-ejecutivo:node/71
  $menu_links['menu-resultados-consulta_directriz-para-el-cumplimiento-efectivo-del-derecho-de-acceso-a-la-informacin-pblica-en-el-poder-ejecutivo:node/71'] = array(
    'menu_name' => 'menu-resultados-consulta',
    'link_path' => 'node/71',
    'router_path' => 'node/%',
    'link_title' => 'Directriz para el cumplimiento efectivo del derecho de acceso a la información pública en el Poder Ejecutivo',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-resultados-consulta_directriz-para-el-cumplimiento-efectivo-del-derecho-de-acceso-a-la-informacin-pblica-en-el-poder-ejecutivo:node/71',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'menu-resultados-consulta_transparencia:<nolink>',
  );
  // Exported menu link: menu-resultados-consulta_educacin-para-la-ciudadana-en-un-gobierno-abierto:node/80
  $menu_links['menu-resultados-consulta_educacin-para-la-ciudadana-en-un-gobierno-abierto:node/80'] = array(
    'menu_name' => 'menu-resultados-consulta',
    'link_path' => 'node/80',
    'router_path' => 'node/%',
    'link_title' => 'Educación para la ciudadanía en un Gobierno Abierto',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-resultados-consulta_educacin-para-la-ciudadana-en-un-gobierno-abierto:node/80',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'menu-resultados-consulta_participacin-ciudadana:<nolink>',
  );
  // Exported menu link: menu-resultados-consulta_estrategia-nacional-por-la-transparencia-anticorrupcin-y-probidad-tap-costa-rica:node/77
  $menu_links['menu-resultados-consulta_estrategia-nacional-por-la-transparencia-anticorrupcin-y-probidad-tap-costa-rica:node/77'] = array(
    'menu_name' => 'menu-resultados-consulta',
    'link_path' => 'node/77',
    'router_path' => 'node/%',
    'link_title' => 'Estrategia nacional por la transparencia, anticorrupción y probidad (TAP-Costa Rica)',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-resultados-consulta_estrategia-nacional-por-la-transparencia-anticorrupcin-y-probidad-tap-costa-rica:node/77',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'menu-resultados-consulta_lucha-contra-la-corrupcin:<nolink>',
  );
  // Exported menu link: menu-resultados-consulta_estrategia-para-la-discusin-de-la-ley-de-acceso-a-la-informacin-pblica:node/72
  $menu_links['menu-resultados-consulta_estrategia-para-la-discusin-de-la-ley-de-acceso-a-la-informacin-pblica:node/72'] = array(
    'menu_name' => 'menu-resultados-consulta',
    'link_path' => 'node/72',
    'router_path' => 'node/%',
    'link_title' => 'Estrategia para la discusión de la ley de Acceso a la Información Pública',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-resultados-consulta_estrategia-para-la-discusin-de-la-ley-de-acceso-a-la-informacin-pblica:node/72',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'menu-resultados-consulta_transparencia:<nolink>',
  );
  // Exported menu link: menu-resultados-consulta_estrategia-para-la-discusin-de-una-modificacin-legal-para-el-uso-de-una-plataforma-nica-de-compras-pblicas:node/75
  $menu_links['menu-resultados-consulta_estrategia-para-la-discusin-de-una-modificacin-legal-para-el-uso-de-una-plataforma-nica-de-compras-pblicas:node/75'] = array(
    'menu_name' => 'menu-resultados-consulta',
    'link_path' => 'node/75',
    'router_path' => 'node/%',
    'link_title' => 'Estrategia para la discusión de una modificación legal para el uso de una plataforma única de compras públicas',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-resultados-consulta_estrategia-para-la-discusin-de-una-modificacin-legal-para-el-uso-de-una-plataforma-nica-de-compras-pblicas:node/75',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'menu-resultados-consulta_lucha-contra-la-corrupcin:<nolink>',
  );
  // Exported menu link: menu-resultados-consulta_herramientas-y-mecanismos-para-el-gobierno-abierto:<nolink>
  $menu_links['menu-resultados-consulta_herramientas-y-mecanismos-para-el-gobierno-abierto:<nolink>'] = array(
    'menu_name' => 'menu-resultados-consulta',
    'link_path' => '<nolink>',
    'router_path' => '<nolink>',
    'link_title' => 'Herramientas y mecanismos para el gobierno abierto',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-resultados-consulta_herramientas-y-mecanismos-para-el-gobierno-abierto:<nolink>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: menu-resultados-consulta_introduccin:node/69
  $menu_links['menu-resultados-consulta_introduccin:node/69'] = array(
    'menu_name' => 'menu-resultados-consulta',
    'link_path' => 'node/69',
    'router_path' => 'node/%',
    'link_title' => 'Introducción',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-resultados-consulta_introduccin:node/69',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-resultados-consulta_laboratorios-cvicos:node/85
  $menu_links['menu-resultados-consulta_laboratorios-cvicos:node/85'] = array(
    'menu_name' => 'menu-resultados-consulta',
    'link_path' => 'node/85',
    'router_path' => 'node/%',
    'link_title' => 'Laboratorios cívicos',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-resultados-consulta_laboratorios-cvicos:node/85',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'menu-resultados-consulta_participacin-ciudadana:<nolink>',
  );
  // Exported menu link: menu-resultados-consulta_lucha-contra-la-corrupcin:<nolink>
  $menu_links['menu-resultados-consulta_lucha-contra-la-corrupcin:<nolink>'] = array(
    'menu_name' => 'menu-resultados-consulta',
    'link_path' => '<nolink>',
    'router_path' => '<nolink>',
    'link_title' => 'Lucha contra la corrupción',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-resultados-consulta_lucha-contra-la-corrupcin:<nolink>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'menu-resultados-consulta_normativa-y-polticas-para-el-gobierno-abierto:<nolink>',
  );
  // Exported menu link: menu-resultados-consulta_normativa-y-polticas-para-el-gobierno-abierto:<nolink>
  $menu_links['menu-resultados-consulta_normativa-y-polticas-para-el-gobierno-abierto:<nolink>'] = array(
    'menu_name' => 'menu-resultados-consulta',
    'link_path' => '<nolink>',
    'router_path' => '<nolink>',
    'link_title' => 'Normativa y políticas para el gobierno abierto',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-resultados-consulta_normativa-y-polticas-para-el-gobierno-abierto:<nolink>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-resultados-consulta_participacin-ciudadana:<nolink>
  $menu_links['menu-resultados-consulta_participacin-ciudadana:<nolink>'] = array(
    'menu_name' => 'menu-resultados-consulta',
    'link_path' => '<nolink>',
    'router_path' => '<nolink>',
    'link_title' => 'Participación ciudadana',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-resultados-consulta_participacin-ciudadana:<nolink>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'menu-resultados-consulta_normativa-y-polticas-para-el-gobierno-abierto:<nolink>',
  );
  // Exported menu link: menu-resultados-consulta_plataformas-regionales-de-integracin-e-informacin:node/83
  $menu_links['menu-resultados-consulta_plataformas-regionales-de-integracin-e-informacin:node/83'] = array(
    'menu_name' => 'menu-resultados-consulta',
    'link_path' => 'node/83',
    'router_path' => 'node/%',
    'link_title' => 'Plataformas regionales de integración e información',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-resultados-consulta_plataformas-regionales-de-integracin-e-informacin:node/83',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'menu-resultados-consulta_transparencia:<nolink>',
  );
  // Exported menu link: menu-resultados-consulta_poltica-nacional-de-datos-abiertos:node/74
  $menu_links['menu-resultados-consulta_poltica-nacional-de-datos-abiertos:node/74'] = array(
    'menu_name' => 'menu-resultados-consulta',
    'link_path' => 'node/74',
    'router_path' => 'node/%',
    'link_title' => ' Política Nacional de Datos Abiertos',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-resultados-consulta_poltica-nacional-de-datos-abiertos:node/74',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'menu-resultados-consulta_transparencia:<nolink>',
  );
  // Exported menu link: menu-resultados-consulta_poltica-nacional-de-gobierno-digital:node/73
  $menu_links['menu-resultados-consulta_poltica-nacional-de-gobierno-digital:node/73'] = array(
    'menu_name' => 'menu-resultados-consulta',
    'link_path' => 'node/73',
    'router_path' => 'node/%',
    'link_title' => 'Política Nacional de Gobierno Digital',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-resultados-consulta_poltica-nacional-de-gobierno-digital:node/73',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'menu-resultados-consulta_transparencia:<nolink>',
  );
  // Exported menu link: menu-resultados-consulta_programa-de-capacitacin-y-divulgacin-de-los-conceptos-y-valores-de-gobierno-abierto-para-servidores-pblicos:node/76
  $menu_links['menu-resultados-consulta_programa-de-capacitacin-y-divulgacin-de-los-conceptos-y-valores-de-gobierno-abierto-para-servidores-pblicos:node/76'] = array(
    'menu_name' => 'menu-resultados-consulta',
    'link_path' => 'node/76',
    'router_path' => 'node/%',
    'link_title' => 'Programa de capacitación y divulgación de los conceptos y valores de gobierno abierto para servidores públicos',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-resultados-consulta_programa-de-capacitacin-y-divulgacin-de-los-conceptos-y-valores-de-gobierno-abierto-para-servidores-pblicos:node/76',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'menu-resultados-consulta_lucha-contra-la-corrupcin:<nolink>',
  );
  // Exported menu link: menu-resultados-consulta_promocin-de-polticas-de-gobierno-abierto-en-los-gobiernos-locales:node/79
  $menu_links['menu-resultados-consulta_promocin-de-polticas-de-gobierno-abierto-en-los-gobiernos-locales:node/79'] = array(
    'menu_name' => 'menu-resultados-consulta',
    'link_path' => 'node/79',
    'router_path' => 'node/%',
    'link_title' => 'Promoción de políticas de gobierno abierto en los gobiernos locales',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-resultados-consulta_promocin-de-polticas-de-gobierno-abierto-en-los-gobiernos-locales:node/79',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'menu-resultados-consulta_participacin-ciudadana:<nolink>',
  );
  // Exported menu link: menu-resultados-consulta_redes-ciudadanas-para-la-participacin-y-la-colaboracin:node/84
  $menu_links['menu-resultados-consulta_redes-ciudadanas-para-la-participacin-y-la-colaboracin:node/84'] = array(
    'menu_name' => 'menu-resultados-consulta',
    'link_path' => 'node/84',
    'router_path' => 'node/%',
    'link_title' => 'Redes ciudadanas para la participación y la colaboración',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-resultados-consulta_redes-ciudadanas-para-la-participacin-y-la-colaboracin:node/84',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'menu-resultados-consulta_participacin-ciudadana:<nolink>',
  );
  // Exported menu link: menu-resultados-consulta_sistema-para-el-seguimiento-de-obras-de-infraestructura-vial:node/82
  $menu_links['menu-resultados-consulta_sistema-para-el-seguimiento-de-obras-de-infraestructura-vial:node/82'] = array(
    'menu_name' => 'menu-resultados-consulta',
    'link_path' => 'node/82',
    'router_path' => 'node/%',
    'link_title' => 'Sistema para el seguimiento de obras de infraestructura vial',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-resultados-consulta_sistema-para-el-seguimiento-de-obras-de-infraestructura-vial:node/82',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'menu-resultados-consulta_transparencia:<nolink>',
  );
  // Exported menu link: menu-resultados-consulta_transparencia:<nolink>
  $menu_links['menu-resultados-consulta_transparencia:<nolink>'] = array(
    'menu_name' => 'menu-resultados-consulta',
    'link_path' => '<nolink>',
    'router_path' => '<nolink>',
    'link_title' => 'Transparencia',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-resultados-consulta_transparencia:<nolink>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'menu-resultados-consulta_normativa-y-polticas-para-el-gobierno-abierto:<nolink>',
  );
  // Translatables
  // Included for use with string extractors like potx.
  t('Campaña de divulgación de derechos ciudadanos en el marco del gobierno abierto');
  t('Catálogo institucional y guía de acceso ciudadano');
  t('Directriz para el cumplimiento efectivo del derecho de acceso a la información pública en el Poder Ejecutivo');
  t('Educación para la ciudadanía en un Gobierno Abierto');
  t('Estrategia nacional por la transparencia, anticorrupción y probidad (TAP-Costa Rica)');
  t('Estrategia para la discusión de la ley de Acceso a la Información Pública');
  t('Estrategia para la discusión de una modificación legal para el uso de una plataforma única de compras públicas');
  t('Herramientas y mecanismos para el gobierno abierto');
  t('Introducción');
  t('Laboratorios cívicos');
  t('Lucha contra la corrupción');
  t('Normativa y políticas para el gobierno abierto');
  t('Participación ciudadana');
  t('Plataformas regionales de integración e información');
  t('Política Nacional de Gobierno Digital');
  t('Programa de capacitación y divulgación de los conceptos y valores de gobierno abierto para servidores públicos');
  t('Promoción de políticas de gobierno abierto en los gobiernos locales');
  t('Redes ciudadanas para la participación y la colaboración');
  t('Sistema para el seguimiento de obras de infraestructura vial');
  t('Transparencia');
  t(' Política Nacional de Datos Abiertos');


  return $menu_links;
}
