<?php

/**
 * @file
 * Install file for ysga_taxonomy.
 */

/**
 * Implements hook_install().
 */
function ysga_taxonomy_install() {
  // Create 'Plan de acción' vocabulary.
  $plan_vocab = (object) array(
    'name' => 'Planes de acción',
    'description' => 'Planes de acción',
    'machine_name' => 'ysga_plan_vocabulary',
  );
  taxonomy_vocabulary_save($plan_vocab);

  // Create 'Plan de acción' vocabulary terms.
  $term_names = array(
    'Segundo Plan (2015)',
    'Tercer Plan (2017)',
  );
  $plan_vocab = taxonomy_vocabulary_machine_name_load('ysga_plan_vocabulary');
  foreach ($term_names as $name) {
    $term = (object) array(
      'name' => $name,
      'vid' => $plan_vocab->vid,
    );
    taxonomy_term_save($term);
  }

}
